### ISSUE TITLE
Get transcribed text

### ISSUE THREAD

**Issue by Aaryan-Umar** [AIWintermuteAI/WhisperLive#8]
I can't get the transcribed text from the terminal

I've checked client.py line 123 (https://github.com/collabora/WhisperLive/issues/220) and have found nothing like the utils.print_transcript(text) he is talking about.

Is there any way to get the transcibed text as a variable so I can use it further in my python program.
Lastly, what is the output.srt the other github issue is talking about? Is there any way to use that file to get the transcribed text

**Comment by AIWintermuteAI** [comment]
I explained the changes I made in the video
https://youtu.be/3yLFWpKKbe8?si=bGFOZIeqUl6H_IvK&t=285
you can also see 
https://github.com/AIWintermuteAI/WhisperLive/blob/main/examples/example_client.py

Basically you get the transcribed text in that callback function - the function [here](https://github.com/AIWintermuteAI/WhisperLive/blob/main/examples/example_client.py) is an example only, so you will likely need to modify it. But it should give you an idea.

**Comment by Aaryan-Umar** [comment]
I ran the example code and I get this error:
TypeError: TranscriptionClient.__init__() got an unexpected keyword argument 'callback'
The code is an exact copy and paste of your code.
Did you get this error as well or am I doing something wrong?


EDIT: fixed the issue 
Appreciate the work you've done

**Comment by julien-nc** [comment]
@Aaryan-Umar How did you solve the issue on your side? I'm trying to use a custom callback function and I'm facing the same issue.

**Comment by Aaryan-Umar** [comment]
@julien-nc 
Try rebuilding the source code or trying to reinstall it. I don't remember the exact steps that I took because of how long it has been, but in the end, there was no code wrong on the example_client.py file. Also check [this](https://youtu.be/3yLFWpKKbe8?si=EPh-emupmWnLHdon&t=310) for more info. If anything jogs my memory, or if I dig through my files and find something else, i'll let you know. In the end, i'm pretty sure I just reinstalled it and made sure that the fork was updated.

**Comment by Aaryan-Umar** [comment]
Here's my client.py and server.py, located in whisper_live/

[client - Copy (1).txt](https://github.com/user-attachments/files/19376617/client.-.Copy.1.txt)
[server - Copy.txt](https://github.com/user-attachments/files/19376616/server.-.Copy.txt)
